version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.react
    image: sakit333/frontend:latest   # Image name for Docker Hub
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.springboot
    image: sakit333/backend:latest   # Image name for Docker Hub
    ports:
      - "8081:8081"
